# Generated by Django 3.0.14 on 2022-01-22 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_customer_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='username',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
