# Generated by Django 4.1.1 on 2022-09-12 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0012_auto_20220206_1951'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='user_email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
