# Generated by Django 3.0.14 on 2022-01-22 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_auto_20220119_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='password',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
