# Generated by Django 3.0.14 on 2022-02-04 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_remove_customer_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='reward_point',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
