# Generated by Django 3.0.14 on 2022-02-19 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_notification_owner_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='notification',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='notification',
            name='owner',
        ),
    ]
