# Generated by Django 3.0.14 on 2022-02-08 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_auto_20220202_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='no_of_times_bought',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
