# Generated by Django 3.0.14 on 2022-02-04 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_auto_20220119_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='used_discount_points',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
