# Generated by Django 3.0.14 on 2022-02-04 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_orderproduct_used_discount_points'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='used_discount_points',
        ),
        migrations.AddField(
            model_name='order',
            name='used_discount_points',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
