# Generated by Django 3.0.14 on 2022-02-02 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20220119_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='choice',
            field=models.CharField(blank=True, choices=[('New Arrivals', 'New Arrivals'), ('Pets', 'Pets'), ('Pet Accessories', 'Pet Accessories'), ('Pet food', 'Petfood'), ('Aquariums', 'Aquariums')], max_length=300, null=True),
        ),
    ]
