# Generated by Django 3.0.14 on 2022-02-02 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_product_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='choice',
            field=models.CharField(blank=True, choices=[('New Arrivals', 'New Arrivals'), ('Pets', 'Pets'), ('Pet Accessories', 'Pet Accessories'), ('Pet food', 'Pet food'), ('Aquariums', 'Aquariums')], max_length=300, null=True),
        ),
    ]
