# Generated by Django 3.0.14 on 2022-02-08 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_auto_20220208_1746'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='no_of_times_bought',
            new_name='buy_count',
        ),
    ]
