# Generated by Django 3.0.14 on 2022-02-08 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_auto_20220208_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, default='New Arrivals', null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.Category'),
        ),
    ]
